### ISSUE TITLE
could provide a rust-compatible version?

### ISSUE THREAD

**Issue by insinfo** [brechtsanders/winlibs_mingw#78]
could provide a rust-compatible version?

I'm trying to compile a "hello world" in rust on windows with the lib "ssh2" and "whoami" and I'm getting errors

```
PS C:\MyRustProjects\fsbackup_engine> cargo clean
PS C:\MyRustProjects\fsbackup_engine> cargo build
   Compiling cfg-if v1.0.0
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling pkg-config v0.3.22
   Compiling libc v0.2.108
   Compiling cc v1.0.72
   Compiling autocfg v1.0.1
   Compiling winapi v0.3.9
   Compiling proc-macro2 v1.0.32
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.81
   Compiling parking_lot_core v0.8.5
   Compiling memchr v2.4.1
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.7.0
   Compiling serde v1.0.130
   Compiling log v0.4.14
   Compiling whoami v1.2.0
   Compiling ppv-lite86 v0.2.15
   Compiling regex-syntax v0.6.25
   Compiling bitflags v1.3.2
   Compiling lazy_static v1.4.0
   Compiling bytesize v1.1.0
   Compiling path-slash v0.1.4
   Compiling wildmatch v2.1.0
   Compiling getrandom v0.2.3
   Compiling instant v0.1.12
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling lock_api v0.4.5
   Compiling libz-sys v1.1.3
   Compiling libssh2-sys v0.2.23
   Compiling rand_core v0.6.3
   Compiling rand_chacha v0.3.1
   Compiling quote v1.0.10
   Compiling aho-corasick v0.7.18
   Compiling rand v0.8.4
   Compiling time v0.1.44
   Compiling toml v0.5.8
   Compiling regex v1.5.4
   Compiling parking_lot v0.11.2
   Compiling chrono v0.4.19
   Compiling thiserror-impl v1.0.30
   Compiling thiserror v1.0.30
   Compiling ssh2 v0.9.3
   Compiling fsbackup_engine v0.1.0 (C:\MyRustProjects\fsbackup_engine)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\rust\\toolchains\\stable-x86_64-pc-win
dows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.1ui50u8fuayzqe56.rcgu.o" "C:\\M
yRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.1xmc7zjivlfp8nr8.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-
8e2c4106c9585f5a.223d2pvdkolzzaqw.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.22frl8ln2pls2y4p.rcgu.o" "C:\\MyRustProjects\\fsback
up_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.29q70kd8jhiontt5.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.2b2k
d6pyvgp93dly.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.35j07855z6n3sbqy.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\de
bug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3bhog7do8ojuvl79.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3hzsrkewdsdtt95l.rcgu.o"
"C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3tqf3lof41unxyro.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_e
ngine-8e2c4106c9585f5a.bve6146ji1dzqnd.rcgu.o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.3mxtcd1b58wzia2z.rcgu.o" "-L" "C:\\MyRustProjec
ts\\fsbackup_engine\\target\\debug\\deps" "-L" "C:\\rust\\cargo\\registry\\src\\github.com-1ecc6299db9ec823\\winapi-x86_64-pc-windows-gnu-0.4.0\\lib" "-L" "C:\\MyRustProjects\\fsbackup_e
ngine\\target\\debug\\build\\libssh2-sys-fc7c71d01a27467b\\out\\build" "-L" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\build\\libz-sys-5c77173b41a8a041\\out\\lib" "-L" "C:\\MyR
ustProjects\\fsbackup_engine\\target\\debug\\build\\libz-sys-5c77173b41a8a041\\out\\lib" "-L" "C:\\windows\\system32" "-L" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustl
ib\\x86_64-pc-windows-gnu\\lib" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-c949a5d9f8ea17eb.
rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-4efbd26dc95f473b.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-window
s-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-11df657f271ec0b5.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr
-ed6e817a89285a21.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-a16c4de5bb48a9a6.rlib" "C:\\rust\\toolchains\\stable-x
86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-b5d4a31ea91f9e86.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\
lib\\libstd_detect-01e22831e506e0c6.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-85865d75ad690c5e.rlib" "C:\\rus
t\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-91e2696c8ccb4461.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustl
ib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-186512436a4043bc.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwi
nd-d0f4aee65f54d86f.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-42335e6cb2553e87.rlib" "C:\\rust\\toolchains\\stable-x8
6_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-662baf24e2595e01.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\li
b\\liballoc-131219d6deabaad8.rlib" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-6530d4af942dc9d4.rlib" "C:\\
rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-d1ec034e2d5fe483.rlib" "-Wl,--end-group" "C:\\rust\\toolchains\\stable-x86_64-pc-windows
-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-885492184211f20a.rlib" "-Wl,-Bdynamic" "-lkernel32" "-lws2_32" "-ladvapi32" "-luserenv" "-lkernel32" "-lgcc_eh" "-l:l
ibpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "C:\\rust\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64
-pc-windows-gnu\\lib" "-o" "C:\\MyRustProjects\\fsbackup_engine\\target\\debug\\deps\\fsbackup_engine-8e2c4106c9585f5a.exe" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "C:\\rust\\tool
chains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/programdata/chocolatey/lib/ming
w/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o:crtexe.c:(.text+0x4e): undefined reference to `__p__fmode'
          c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/programdata/chocolatey/lib/ming
w/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o:crtexe.c:(.text+0x5e): undefined reference to `__p__commode'
          c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/programdata/chocolatey/lib/ming
w/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o:crtexe.c:(.text+0x339): undefined reference to `_set_invalid_parameter_h
andler'
          c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/programdata/chocolatey/lib/ming
w/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o:crtexe.c:(.text+0x354): undefined reference to `__p__acmdln'
          c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/programdata/chocolatey/lib/ming
w/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-merr.o):merr.c:(.text+0xd0): undefined referenc
e to `__acrt_iob_func'
          c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/programdata/chocolatey/lib/ming
w/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o):pseudo-reloc.c:(.text+0x29): un
defined reference to `__acrt_iob_func'
          c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/programdata/chocolatey/lib/ming
w/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o):pseudo-reloc.c:(.text+0x54): un
defined reference to `__acrt_iob_func'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-li
bkindname)

error: could not compile `fsbackup_engine` due to previous error
PS C:\MyRustProjects\fsbackup_engine>

```
#### Cargo.toml
```toml
[package]
name = "fsbackup_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.0" # Bindings to libssh2 for interacting with SSH servers and executing remote commands
whoami = "1.2.0" # Retrieve the current user and environment.
toml = "0.5.8" # A native Rust encoder and decoder of TOML-formatted files and streams.
rand = "0.8.4" # Random number generators and other randomness functionality.
regex = "1.5.4" # An implementation of regular expressions
lazy_static = "1.4.0" # A macro for declaring lazily evaluated statics
log = "0.4.14" # A lightweight logging facade for
bytesize = "1.1.0" # an utility for human-readable bytes representations
chrono = "0.4.19" # Date and time library
wildmatch = "2.0.0" # Simple string matching with questionmark and star wildcard operator.
thiserror = "^1.0.0" # provides a convenient derive macro for the standard library's std::error::Error trait.

[target."cfg(target_family = \"unix\")"]
[target."cfg(target_family = \"unix\")".dependencies]
users = "0.11.0" # Library for accessing Unix users and groups

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.1.4" # Conversion to\from a file path from/to slash path

```
